create table member (
                        id bigint generated by default as identity,
                        access_token varchar(255),
                        email varchar(255),
                        nick_name varchar(255),
                        primary key (id)
);
